-- Actualizar módulo 122 (Footer) en español
UPDATE oc_module 
SET setting = JSON_SET(
    setting,
    '$.module_description."2".description',
    '<div class="footer-column col-sm-12 col-md-4">\n\t<a href="#" class="logo-footer"><img src="/image/catalog/Logo_Home.png" style="max-width:200px" alt="logo-footer"></a>\n\t<p class="about-text">\n\t\tBienvenido al Universo HOP, donde la creatividad y la diversi&oacute;n se encuentran en cada producto.\n\t</p>\n\t<ul class="bottom-menu">\n\t\t<li><a href="index.php?route=information/contact">Cont&aacute;ctanos</a></li>\n\t\t<li><a href="index.php?route=information/information&amp;information_id=5">T&eacute;rminos</a></li>\n\t\t<li><a href="index.php?route=information/information&amp;information_id=3">Privacidad</a></li>\n\t</ul>\n\t<p class="copyright">\n\t\tCopyright &copy; 2025&nbsp;<a href="https://frubik.com/" style="background-color: rgb(255, 255, 255);">Frubik</a>. Todos los Derechos Reservados.\n\t</p>\n</div>\n\n<div class="footer-column col-sm-12 col-md-2">\n\t<h3 class="footer-title">Mi Cuenta</h3>\n\t<ul class="footer-menu">\n\t\t<li><a href="index.php?route=account/account">Mi Cuenta</a></li>\n\t\t<li><a href="index.php?route=account/login">Iniciar Sesi&oacute;n</a></li>\n\t\t<li><a href="index.php?route=checkout/cart">Mi Carrito</a></li>\n\t\t<li><a href="index.php?route=account/wishlist">Lista de Deseos</a></li>\n\t\t<li><a href="index.php?route=checkout/checkout">Finalizar Compra</a></li>\n\t</ul>\n</div>\n\n<div class="footer-column col-sm-12 col-md-2">\n\t<h3 class="footer-title">Informaci&oacute;n</h3>\n\t<ul class="footer-menu">\n\t\t<li>\n\t\t\t<a href="index.php?route=information/information&amp;information_id=4">Sobre Nosotros</a>\n\t\t</li>\n\t\t<li>\n\t\t\t<a href="index.php?route=information/information&amp;information_id=7">Enlace de Informaci&oacute;n</a>\n\t\t</li>\n\t\t<li>\n\t\t\t<a href="index.php?route=information/information&amp;information_id=6">Informaci&oacute;n de Env&iacute;o</a>\n\t\t</li>\n\t\t<li>\n\t\t\t<a href="index.php?route=information/information&amp;information_id=3">Pol&iacute;tica de Privacidad</a>\n\t\t</li>\n\t\t<li>\n\t\t\t<a href="index.php?route=information/information&amp;information_id=5">T&eacute;rminos y Condiciones</a>\n\t\t</li>\n\t</ul>\n</div>\n\n<div class="footer-column col-sm-12 col-md-4">\n\t<div class="social-icon">\n\t\t<p>S&iacute;guenos:</p>\n\t\t<ul>\n\t\t\t<li>\n\t\t\t\t<a href="https://www.instagram.com/hopuniverse/"><i class="fa fa-instagram"></i></a>\n\t\t\t</li>\n\t\t\t<li>\n\t\t\t\t<a href="https://www.tiktok.com/@hopuniverse"><i class="fa fa-tiktok"></i></a>\n\t\t\t</li>\n\t\t\t<li>\n\t\t\t\t<a href="https://www.youtube.com/@hopuniverse"><i class="fa fa-youtube-play"></i></a>\n\t\t\t</li>\n\t\t</ul>\n\t</div>\n\t<div class="payment">\n\t\t<p>M&eacute;todos de Pago:</p>\n\t\t<img src="image/catalog/payment-icon.png" alt="payment-icon">\n\t</div>\n</div>\n'
)
WHERE module_id = 122;

